### ISSUE TITLE
Bump up env/CI to Python >=3.8

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/kissim#118]
## Description
Bump up env/CI to Python 3.8, 3.9, and 3.10.
Triggered by new `pandas` release 2.0.0, which is only available for Python >= 3.8, see https://pandas.pydata.org/docs/getting_started/install.html#python-version-support

## Todos

- [ ] Apply latest `cookiecutter-cms` template
  - [ ] TBD: Bump up CI to Python 3.8, 3.9, and 3.10.
  - [ ] TBD: Bump up env to >= 3.8
- [ ] Update `pandas` API to 2.0.0: https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html
  - [ ] `pd.append` to `pd.concat`
